sudo : required

services : 
  - docker

before_install :
  - docker build -t sunnysultan1640/docker-frontend -f Dockerfile.dev .

script : 
  - docker run sunnysultan1640/docker-frontend npm run test -- --coverage

deploy : 
  provider : elasticbeanstalk
  region : "ap-southeast-1"
  app : "docker-frontend"
  env : "DockerFrontend-env"
  bucket_name : "elasticbeanstalk-ap-southeast-1-320340729443"
  bucket_path : "docker-frontend"
  on:
    branch: master
  access_key_id : $Access_key_ID
  secret_access_key : 
    secure : "$Secret_access_key"